version: "3.0"
services:
  db:
    container_name: "db"
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sa
    ports:
      - "5433:5432"
